Unset Parent on Conductors' Items.Clear()
Caliburn-Micro/Caliburn.Micro pull request #637
Opened 2019-09-24 21:36 UTC by louistio

ObservableCollection<T> is designed so
NotifyCollectionChangedEventArgs.OldItems is not populated when .Clear()
is called on the collection. Because of this, Caliburn conductors can't
unset the Parent property on all conducted IChild.

There are multiple solutions to this issue that have been discussed, but
I feel like adding a new CollectionCleared event to BindableCollection
is the best compromise considering it doesn't break any existing code
and only extends existing ObservableCollection functionality.

2019-09-24 21:38 UTC, louistio commented
More discussion in #465 and on [stackoverflow](https://stackoverflow.com/questions/224155/when-clearing-an-observablecollection-there-are-no-items-in-e-olditems).

2019-09-24 22:13 UTC, louistio commented
```
Caliburn.Micro.Core.Tests.EventAggregatorSubscribing.Caliburn.Micro.Core.Tests.EventAggregatorSubscribing.A_valid_subscriber_is_assigned_as_a_handler_its_message_type
Assert.True() Failure
Expected: True
Actual:   False
```

Not sure why that test is failing, everything is green locally. 🤔

2026-05-24 16:39 UTC, vb2ae requested changes
Thanks for merging in main.   Could you update the version number in version.json to 6.0-beta.  

{
    "$schema": "https://raw.githubusercontent.com/AArnott/Nerdbank.GitVersioning/master/src/NerdBank.GitVersioning/version.schema.json",
    "version": "6.0-beta",
    "nugetPackageVersion": {
        "semVer": 2
    },
    "publicReleaseRefSpec": [
        "^refs/heads/master$"
    ],
    "cloudBuild": {
        "buildNumber": {
            "enabled": true,
            "includeCommitId": {
                "when": "nonPublicReleaseOnly",
                "where": "buildMetadata"
            }
        },
    "setVersionVariables": true
    }
}

2026-05-24 19:33 UTC, adamgauthier commented
@vb2ae Sure, done!

2026-06-03 11:01 UTC, vb2ae approved these changes
Thank you for your pr.   I approve the changes.  I am wondering if we should add a bool property to IChild LegacyMode which will stop setting the parent to null if true. (allow for opt it if breaks their app)

2026-06-03 11:01 UTC, merged

2026-06-12 07:20 UTC, adamgauthier commented
Interesting idea. Honestly, I feel like it's unlikely apps intentionally rely on the old behavior. It was inconsistent with the existing single-item remove/replace semantics, where Parent is already cleared, and the stale Parent reference seems more like an accidental bug.