Initial implementation of WinUI with samples and features working
Caliburn-Micro/Caliburn.Micro pull request #853
Opened 2023-04-06 06:41 UTC by KasperSK

This works but navigation is a little rough around the edges, open for input on how it should be done for WinUI

2023-04-08 14:24 UTC, vb2ae approved these changes

2023-04-08 14:26 UTC, vb2ae commented on src/Caliburn.Micro.WinUI3/Class1.cs
really dont need this file

2023-04-08 16:38 UTC, KasperSK commented on src/Caliburn.Micro.WinUI3/Class1.cs
You are right! Default files 😅 What do you think about the way navigation is done in the Features project? I am unsure if we should change displayrootview to not set a frame as per default since the navigation UI needs to be user supplied.

2023-04-08 17:11 UTC, vb2ae commented on src/Caliburn.Micro.WinUI3/Class1.cs
To answer your question yes the user should supply the frame.

Does this work with desktop, uap or both?

2023-04-08 17:23 UTC, KasperSK commented on src/Caliburn.Micro.WinUI3/Class1.cs
In UAP the bootstrapper creates the frame. How ever there is an overwrite that enables the user to create the frame themselves. But since the UI in UAP is setup to have the back button in the window chrome it is not an issue. 

I focused on WinUI in desktop since reading about the subject that was the direction things where going and UAP was on the way out.

2023-05-06 19:54 UTC, vb2ae commented
@KasperSK do you want to complete this pr?

2023-05-09 04:41 UTC, KasperSK commented
> @KasperSK do you want to complete this pr?

Yes but I think I need to make another commit and fix the small issues. :)

2024-01-11 23:33 UTC, alex-nicholas commented
Just wondering how far off we are from seeing this in a release?

I've been using caliburn.micro in WPF apps for nearly 8 years, but I'm currently working on a WinUI app, and the amount of non-sense you have to do for basic View/ViewModel binding (and the amount of concrete references you need to have from the view to the view model) is just staggering after working in a fully auto-wired caliburn app...

2024-11-05 13:32 UTC, KasperSK commented
@vb2ae Do you still think we should merge this if I rebase the PR?

2024-11-05 13:38 UTC, vb2ae commented
yes we can fix any bug we find

2024-11-05 13:44 UTC, vb2ae commented
@KasperSK thanks

2024-12-18 12:47 UTC, vb2ae commented on src/Caliburn.Micro.WinUI3/Caliburn.Micro.WinUI3.csproj
> +    <TargetFramework>net6.0-windows10.0.19041.0</TargetFramework>
could you change this to net8.0-windows10.0.19041    .net 6 is no longer supported

2024-12-18 12:47 UTC, vb2ae commented on src/Caliburn.Micro.WinUI3/Caliburn.Micro.WinUI3.csproj
> +    <RuntimeIdentifiers>win10-x86;win10-x64;win10-arm64</RuntimeIdentifiers>
could you change this to 
    <RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>

2024-12-18 12:47 UTC, vb2ae commented on src/Caliburn.Micro.Platform/XamlPlatformProvider.cs
> +            var dummy = dispatcher.TryEnqueue(() => action());
probably should be _ = dispatcher.TryEnqueue(() => action());

2024-12-18 12:47 UTC, vb2ae commented on src/Caliburn.Micro.Platform/BindingScope.cs
> +#if WINDOWS_UWP || WinUI3
dont think this is showing on right line.   the 2 { e.Header as DependencyObject } can change to { e.Header }

2024-12-18 12:48 UTC, vb2ae commented on src/Caliburn.Micro.Platform/BindingScope.cs
> +#if WINDOWS_UWP || WinUI3
dont think this is showing on right line.   the 2 { e.Header as DependencyObject } can change to { e.Header }

2024-12-18 12:49 UTC, vb2ae commented on src/Caliburn.Micro.Platform/XamlPlatformProvider.cs
> +            var dummy = dispatcher.TryEnqueue(() => action());
should change to _  = dispatcher.TryEnqueue(() => action());

2024-12-18 12:51 UTC, vb2ae requested changes
just need to move to .net8.0 from .net6.0 which is no longer supported

2024-12-18 12:51 UTC, KasperSK commented
> just need to move to .net8.0 from .net6.0 which is no longer supported

I will get on that :)

2025-01-09 23:08 UTC, vb2ae commented on src/Caliburn.Micro.Platform/XamlPlatformProvider.cs
> +            var dummy = dispatcher.TryEnqueue(() => action());
will fix in future release

2025-01-09 23:08 UTC, vb2ae commented on src/Caliburn.Micro.Platform/XamlPlatformProvider.cs
> +        private DispatcherQueue dispatcher;
Will fix in a future release

2025-01-10 01:20 UTC, vb2ae commented on src/Caliburn.Micro.Platform/XamlPlatformProvider.cs
> +            var dummy = dispatcher.TryEnqueue(() => action());
will fix in a later release

2025-01-10 01:20 UTC, vb2ae commented on src/Caliburn.Micro.Platform/XamlPlatformProvider.cs
> +        private CoreDispatcher dispatcher;
will fix in a later release

2025-01-11 15:01 UTC, vb2ae approved these changes
Looks good made the requested change

2025-01-11 15:05 UTC, KasperSK commented
Thanks Ken, I have not had any time over the holidays. I will merge this and then we should work with WinUI 3 :)

2025-01-11 15:05 UTC, merged

2025-01-11 16:00 UTC, vb2ae commented
@KasperSK no problem.  Hope you enjoyed the holidays